language: node_js
node_js:
  - "0.11"
after_success:
  - git clone -b fix-lambda-publish https://github.com/wtcross/dpl.git ${HOME}/dpl
  - chmod +x ${HOME}/dpl/bin/dpl
  - cd ${HOME}/dpl
  - bundle install
  - cd -
  - rm -rf ./node_modules
  - npm install --production
  - ${HOME}/dpl/bin/dpl --provider=lambda --access_key_id=${AWS_ACCESS_KEY} --description="TravisCI Lambda Provider Test" --secret_access_key=${AWS_SECRET_KEY} --function_name='test-lambda' --role=${LAMBDA_ROLE} --handler_name='handler'
